add_newline = true

scan_timeout = 10

format = """
[â”Œâ”€â”€](white)$directory$git_branch$git_status$hostname
[â””â”€](white)$character(white)"""
# ï„
#[â”‚](white)$directory$hostname

[character]
success_symbol = "[ðŸ‘ ðŸ³ ](#50fa7b) [ï˜½](#ff79c6)"
# \\[à¹‘á´–â—¡á´–à¹‘\\]ðŸ³
error_symbol = "[ðŸ‘ ðŸ³ ](#ff5555) [ï˜½](#ff79c6)"
# \\[à¹‘>_<à¹‘\\]
vicmd_symbol = "[ðŸ‘ ðŸ³ ](#f1fa8c) [ï˜½](#ff79c6)"
# \\[à¹‘á´–â—¡á´–à¹‘\\]

[directory]
truncation_length = 5
format = " [$read_only]($read_only_style)[$path](bold underline #f1fa8c) "

[hostname]
ssh_only = false
format = "on [$hostname](bold #8be9fd)"
