add_newline = true

scan_timeout = 10
command_timeout = 1000

format = """
[â”Œâ”€â”€](#d9ced9)$directory$git_branch$git_status
[â””â”€ï„](#d9ced9)$character(#d9ced9)"""

[character]
success_symbol = "[ ğŸ³ ](#9abf86)[ ï˜½](#d9c77e)"
error_symbol = "[ ğŸ³ ](#d9989c)[ ï˜½](#d9c77e)"
vicmd_symbol = "[ ğŸ³ ](#d9c77e)[ ï˜½](#d9c77e)"

[directory]
truncation_length = 5
format = " [$read_only]($read_only_style)<[$path](bold underline #a6b4de)>"

[hostname]
ssh_only = false
format = "on [$hostname](bold #86bfb6)"

[git_branch]
style = "bold green"
format = "::[$branch $symbol](bold green)"
